apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ssl-cert-issuer-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: connectalwin@gmail.com
    # Name of a secret used to store the ACME account private key
    # privateKeySecretRef will be automatically configured in cluster- no manual config required
    privateKeySecretRef:
      name: letsencrypt-ssl-cert-key
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Instructions:
# Reference for configuration: https://cert-manager.io/docs/installation/kubectl/
# Apply following command in cluster to configure cert-manager: 
# - kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
# Check status of cert-manager pods by running the following command
#  - kubectl get pods --namespace cert-manager
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -