# ========================================= CD - Deploy - Manifests =========================================

name: CD - Deploy - Manifests

on:
  push:
    branches:
      - production
    paths:
      - "infra/**"

jobs:
  Deploy-Manifests-CD-Pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
