# ========================================= CI - Tests - Tickets Service =========================================

name: CI - Tests - Tickets Service

on:
  pull_request:
    paths:
      - "tickets/**"

jobs:
  Tickets-Service-Pre-Integration-Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cd tickets && npm install && npm run test:ci
